# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='sidebar',
            old_name='onwer',
            new_name='owner',
        ),
    ]
